export const SET_USER_WALLET = 'USER ACTION SET USER WALLET';

export const SET_LOADING = 'FLOW ACTION SET LOADING';

export const SET_BET_STATS_DATA = 'TRANSACTION ACTION SET BET STATS DATA';
export const SET_TRIPLE_INFORMATION = 'TRANSACTION ACTION SET TRIPLE INFORMATION';
export const SET_SINGLE_INFORMATION = 'TRANSACTION ACTION SET SINGLE INFORMATION';

export const SET_MATCH = 'MATCH ACTION SET MATCH';

export const SET_WCI_ALLOWANCE = 'WCI ACTION SET WCI ALLOWANCE';

export const SET_COLLATERALS = 'COLLATERAL ACTION SET COLLATERALS';
export const SET_USDT_ALLOWANCE = 'COLLATERAL ACTION SET USDT ALLOWANCE';
export const SET_USDC_ALLOWANCE = 'COLLATERAL ACTION SET USDC ALLOWANCE';
export const SET_SHIB_ALLOWANCE = 'COLLATERAL ACTION SET SHIB ALLOWANCE';
export const SET_DOGE_ALLOWANCE = 'COLLATERAL ACTION SET DOGE ALLOWANCE';