export const SET_USER_WALLET = 'USER ACTION SET USER WALLET';

export const SET_LOADING = 'FLOW ACTION SET LOADING';

export const SET_EARNINGS = 'TRANSACTION ACTION SET EARNINGS';
export const SET_MULTIPLIERS = 'TRANSACTION ACTION SET MULTIPLIERS';
export const SET_BET_STATUS = 'TRANSACTION ACTION SET BET STATUS';
export const SET_BET_RESULT = 'TRANSACTION ACTION SET BET RESULT';
export const SET_BET_AMOUNT = 'TRANSACTION ACTION SET BET AMOUNT';
export const SET_TOTAL_BET = 'TRANSACTION ACTION SET TOTAL BET';
export const SET_CLAIM_HISTORY = 'TRANSACTION ACTION SET CLAIM HISTORY';